name: Test runner

on:
  push:
  workflow_dispatch:

jobs:
  install-kubectl:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: sillsdev/common-github-actions/install-kubectl@main
      -
        run: kubectl version
